[package]
name = "qjs-extensions"
version = "0.1.0"
edition = "2021"


[dependencies]
qjs = { package = "qjsbind", version = "0.1.0", default-features = false, path = "../qjsbind" }
base64 = { version = "0.21", optional = true }
sha1 = { version = "0.10", optional = true }
sha2 = { version = "0.10", optional = true }
sha3 = { version = "0.10", optional = true }
blake2 = { version = "0.10", optional = true }
md5 = { version = "0.7", optional = true }
hex = { version = "0.4", optional = true }
hex_fmt = { version = "0.3", optional = true }

[features]
default = ["base64", "sha1", "sha2", "sha3", "blake2", "hex"]
hex = ["dep:hex", "hex_fmt"]
std = ["qjs/std"]
