[package]
name = "qjsbind"
version = "0.1.0"
edition = "2021"

[dependencies]
qjs-sys = { path = "../qjs-sys" }
qjsbind-derive = { path = "../qjsbind-derive" }

hex = "0.4"
cstr = "0.2"
tinyvec = "1"
scopeguard = "1"

[features]
default = ["std"]
std = []
with-polyfills = ["qjs-sys/with-polyfills"]
sanitize-address = ["qjs-sys/sanitize-address"]